name: eurotempl
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python
  - freecad=0.21.1
  - postgresql
  - redis-py
  - gdal
  - numpy
  - cmake
  - cgal
  - pybind11
  - occt=7.6.3
  - occt
  - pip
  - pyqt=5.15.7
  - pip:
    - django
    - djangorestframework
    - pytest
    - pytest-django
    - pytest-asyncio
    - black
    - flake8
    - isort
    - mypy
    - django-cors-headers
    - python-dotenv
    - django-environ
    - django-extensions
    - semver
    - cadquery
    - psycopg2-binary