name: EuroTempl
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - postgresql=15
  - redis-py
  - django
  - djangorestframework
  - pytest
  - pytest-django
  - freecad
  - gdal
  - libgdal
  - pip
  - pythreejs
  - pyside6
  - occt
  - pythonocc-core
  - ifcopenshell
  - pip:
    - django-cors-headers
    - python-dotenv
    - psycopg2-binary
    - drf-spectacular
    - postgis
    - semver
    - pytest-asyncio  - cgal
  - cmake
  - cgal
  - pybind11
  - ninja
